[package]
name = "script"
version = "0.1.12"
description = "小工具"
authors = ["kd"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "script_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri = { version = "2.0.0", features = [ "tray-icon" ] }
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [ "tray-icon" ] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
tauri-plugin-sql = "2"
tauri-plugin-store = "2"
tauri-plugin-upload = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-window-state = "2"


